Make out of source build succeed.
Previously, they failed with
"In file included from /home/mblatt/src/dune/current/dune-alugrid/dune/alugrid/impl/2d/grid.cc:3:0:
/home/mblatt/src/dune/current/dune-alugrid/dune/alugrid/impl/2d/grid.h:4:49: fatal error: dune/alugrid/common/alugrid_assert.hh: No such file or directory
compilation terminated.
make[2]: *** [libalugrid_2d_la-grid.lo] Fehler 1"

because the toplevel source dir was not included in the CPPFLAGS.

Signed-off-by: dedner <a.s.dedner@warwick.ac.uk>